# Generated by Django 5.0 on 2024-01-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desname', models.CharField(max_length=20)),
                ('descode', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
