# Generated by Django 5.0 on 2024-01-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0004_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divname', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
