# Generated by Django 5.0 on 2024-01-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0005_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=200)),
                ('area', models.IntegerField(choices=[(1, 'Accountant'), (2, 'Cafeteria'), (3, 'Librarian'), (4, 'Teacher'), (5, 'Other')])),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
